language: csharp
solution: KikNPayUsaEPay.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore KikNPayUsaEPay.sln
after_script:
  - nunit-console UsaepayHelper/bin/Debug/KinNPayUsaEPayUnit.dll
