language: csharp
solution: UsaepayHelper.sln
install:
  - nuget restore UsaepayHelper.sln
  - nuget install NUnit.Runners
script:
  - xbuild /p:Configuration=Release UsaepayHelper.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./UsaepayHelperUnit/bin/Release/UsaepayHelperUnit.dll
