language: csharp
solution: KlikNPayUsaEPay.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore KlikNPayUsaEPay.sln
after_script:
  - nunit-console UsaepayHelper/bin/Debug/KlikNPayPaymentUnit.dll
