language: csharp
solution: KinNPayUsaEPay.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore KinNPayUsaEPay.sln
after_script:
  - nunit-console UsaepayHelper/bin/Debug/KinNPayUsaEPayUnit.dll
