language: csharp
solution: UsaepayHelper.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore UsaepayHelper.sln
after_script:
  - nunit-console UsaepayHelper/bin/Debug/UsaepayHelper.dll
