language: csharp
solution: UsaepayHelper.sln
install:
  - nuget restore UsaepayHelper.sln
  - nuget install NUnit.Runners
script:
  - xbuild /p:Configuration=Release UsaepayHelper.sln
  - mono ./testrunner/NUnit.Runners/tools/nunit-console.exe ./UsaepayHelperUnit/bin/Release/UsaepayHelperUnit.dll
